"""Add social media fields to SurveyResponse

Revision ID: a1a6a674fb1c
Revises: add_share_results_field
Create Date: 2025-07-02 06:42:47.123278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a6a674fb1c'
down_revision = 'add_share_results_field'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_media_names', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('social_media_lengths', sa.String(length=256), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('share_results',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('share_results',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_column('social_media_lengths')
        batch_op.drop_column('social_media_names')

    # ### end Alembic commands ###
