"""Add selected_ads to survey_response

Revision ID: caafc89d9a5f
Revises: be60d8c3a2a6
Create Date: 2025-06-18 00:24:36.774135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caafc89d9a5f'
down_revision = 'be60d8c3a2a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_click', schema=None) as batch_op:
        batch_op.alter_column('ad_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_ads', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_column('selected_ads')

    with op.batch_alter_table('ad_click', schema=None) as batch_op:
        batch_op.alter_column('ad_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
